## Creating Numpy Arrays

In [1]:
!pip install pandas

In [2]:
 ### Importing the library

SyntaxError: invalid syntax (298874152.py, line 2)

In [3]:
### Importing the library

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [7]:
# 3D array
data_array= np.random.rand(2, 3, 4)
random_data

array([[[0.46316899, 0.16762074, 0.09825964, 0.33681815],
        [0.23856611, 0.1586651 , 0.79552618, 0.93110534],
        [0.08929255, 0.63131293, 0.40553076, 0.04243307]],

       [[0.58846265, 0.07382225, 0.62269637, 0.11072468],
        [0.43028547, 0.29884205, 0.93490238, 0.57543616],
        [0.3889291 , 0.4663487 , 0.06779454, 0.95469526]]])

### A matrix with all zeros

In [10]:
zeros = np.zeros((2, 2, 2))
zeros

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [11]:
ones = np.ones((2, 2, 2))
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [12]:
type(ones[1][1][1])

numpy.float64

In [17]:
full = np.full((2, 3, 4), 10)
full

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

### Matrix with different numbers 

In [19]:
matrix_dn = np.matrix(
    [[1, 2, 3, 4],
    [5, 6, 7, 8]],
)
matrix_dn

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

#### Matrix Info

##### Shape of the matrix 

In [20]:
matrix_dn.shape

(2, 4)

#### Number of elements in a matrix

In [22]:
matrix_dn.size

8

#### 1.Why do we need numpy?

#### 2.What are arrays in your machine learning problem?

In [24]:
import pandas as pd

#### Converting a DataFrame to a numpy array 

In [25]:
data_array = data.to_numpy()

NameError: name 'data' is not defined

In [26]:
data_array

NameError: name 'data_array' is not defined

### Slicing

In [30]:
random_data

array([[[0.46316899, 0.16762074, 0.09825964, 0.33681815],
        [0.23856611, 0.1586651 , 0.79552618, 0.93110534],
        [0.08929255, 0.63131293, 0.40553076, 0.04243307]],

       [[0.58846265, 0.07382225, 0.62269637, 0.11072468],
        [0.43028547, 0.29884205, 0.93490238, 0.57543616],
        [0.3889291 , 0.4663487 , 0.06779454, 0.95469526]]])

##### Slicing one matrix out of n-matrix

In [31]:
one_matrix = random_data[0]
one_matrix

array([[0.46316899, 0.16762074, 0.09825964, 0.33681815],
       [0.23856611, 0.1586651 , 0.79552618, 0.93110534],
       [0.08929255, 0.63131293, 0.40553076, 0.04243307]])

##### Slicing couple of rows

In [33]:
row_slicing = random_data[0][0:2]
row_slicing

array([[0.46316899, 0.16762074, 0.09825964, 0.33681815],
       [0.23856611, 0.1586651 , 0.79552618, 0.93110534]])

In [35]:
value_slicing = random_data[1][1][1]
value_slicing 

0.2988420528067238

#### Basic Maths

##### Let's create two matrices

In [37]:
matrix1 = np.random.rand(10)
matrix2 = np.random.rand(10)

In [38]:
matrix1 

array([0.90342312, 0.5958737 , 0.39067655, 0.02633053, 0.12024752,
       0.7850227 , 0.32824942, 0.63633219, 0.68203819, 0.66593065])

In [39]:
matrix2

array([0.81407285, 0.41647058, 0.19864017, 0.24700515, 0.85391874,
       0.65061249, 0.75289301, 0.36057609, 0.96592746, 0.34132527])

### Addition

In [40]:
add = np.add(matrix1, matrix2)
add

array([1.71749597, 1.01234427, 0.58931672, 0.27333568, 0.97416625,
       1.43563519, 1.08114243, 0.99690828, 1.64796566, 1.00725592])

### Subtraction

In [42]:
subtract = np.subtract(matrix1, matrix2)
subtract 

array([ 0.08935027,  0.17940312,  0.19203638, -0.22067462, -0.73367122,
        0.1344102 , -0.4246436 ,  0.27575611, -0.28388927,  0.32460539])

### Division

In [47]:
div = np.divide(matrix1, matrix2)
div

array([1.10975709, 1.43077022, 1.96675501, 0.10659912, 0.14081845,
       1.20659026, 0.43598414, 1.76476538, 0.7060967 , 1.95101482])

### Multipication

In [54]:
mult = np.multiply(matrix1, matrix2)
mult

array([0.73545224, 0.24816386, 0.07760406, 0.00650378, 0.10268161,
       0.51074558, 0.24713669, 0.22944617, 0.65879942, 0.22729896])

### Dot product

In [55]:
dot = np.dot(matrix1, matrix2)
dot 

3.0438323595670838

### Transpose 

In [56]:
# Before transpose

In [57]:
random_data

array([[[0.46316899, 0.16762074, 0.09825964, 0.33681815],
        [0.23856611, 0.1586651 , 0.79552618, 0.93110534],
        [0.08929255, 0.63131293, 0.40553076, 0.04243307]],

       [[0.58846265, 0.07382225, 0.62269637, 0.11072468],
        [0.43028547, 0.29884205, 0.93490238, 0.57543616],
        [0.3889291 , 0.4663487 , 0.06779454, 0.95469526]]])

In [ ]:
# Transpose 

In [60]:
transpose = np.transpose(random_data)
transpose

array([[[0.46316899, 0.58846265],
        [0.23856611, 0.43028547],
        [0.08929255, 0.3889291 ]],

       [[0.16762074, 0.07382225],
        [0.1586651 , 0.29884205],
        [0.63131293, 0.4663487 ]],

       [[0.09825964, 0.62269637],
        [0.79552618, 0.93490238],
        [0.40553076, 0.06779454]],

       [[0.33681815, 0.11072468],
        [0.93110534, 0.57543616],
        [0.04243307, 0.95469526]]])

#### Basic stats 

In [63]:
np.sqrt(random_data[1][1][1])

0.5466644791887652

In [65]:
np.sqrt(25)

5.0

In [66]:
np.abs(2.5)

2.5

In [67]:
np.power(2, 7)

128

In [69]:
np.log(21)

3.044522437723423

In [71]:
np.max(matrix1)

0.9034231196390674

In [72]:
np.min(matrix2)

0.19864017190024008